In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("Speed Dating Data.csv")

In [4]:
data.head()

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [6]:
data.shape

(8378, 195)

In [22]:
data.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8378 entries, 0 to 8377
Data columns (total 195 columns):
iid         int64
id          float64
gender      int64
idg         int64
condtn      int64
wave        int64
round       int64
position    int64
positin1    float64
order       int64
partner     int64
pid         float64
match       int64
int_corr    float64
samerace    int64
age_o       float64
race_o      float64
pf_o_att    float64
pf_o_sin    float64
pf_o_int    float64
pf_o_fun    float64
pf_o_amb    float64
pf_o_sha    float64
dec_o       int64
attr_o      float64
sinc_o      float64
intel_o     float64
fun_o       float64
amb_o       float64
shar_o      float64
like_o      float64
prob_o      float64
met_o       float64
age         float64
field       object
field_cd    float64
undergra    object
mn_sat      object
tuition     object
race        float64
imprace     float64
imprelig    float64
from        object
zipcode     object
income      object
goal        float64
date        float64
go_out      float64
career      object
career_c    float64
sports      float64
tvsports    float64
exercise    float64
dining      float64
museums     float64
art         float64
hiking      float64
gaming      float64
clubbing    float64
reading     float64
tv          float64
theater     float64
movies      float64
concerts    float64
music       float64
shopping    float64
yoga        float64
exphappy    float64
expnum      float64
attr1_1     float64
sinc1_1     float64
intel1_1    float64
fun1_1      float64
amb1_1      float64
shar1_1     float64
attr4_1     float64
sinc4_1     float64
intel4_1    float64
fun4_1      float64
amb4_1      float64
shar4_1     float64
attr2_1     float64
sinc2_1     float64
intel2_1    float64
fun2_1      float64
amb2_1      float64
shar2_1     float64
attr3_1     float64
sinc3_1     float64
fun3_1      float64
intel3_1    float64
amb3_1      float64
attr5_1     float64
sinc5_1     float64
intel5_1    float64
fun5_1      float64
amb5_1      float64
dec         int64
attr        float64
sinc        float64
intel       float64
fun         float64
amb         float64
shar        float64
like        float64
prob        float64
met         float64
match_es    float64
attr1_s     float64
sinc1_s     float64
intel1_s    float64
fun1_s      float64
amb1_s      float64
shar1_s     float64
attr3_s     float64
sinc3_s     float64
intel3_s    float64
fun3_s      float64
amb3_s      float64
satis_2     float64
length      float64
numdat_2    float64
attr7_2     float64
sinc7_2     float64
intel7_2    float64
fun7_2      float64
amb7_2      float64
shar7_2     float64
attr1_2     float64
sinc1_2     float64
intel1_2    float64
fun1_2      float64
amb1_2      float64
shar1_2     float64
attr4_2     float64
sinc4_2     float64
intel4_2    float64
fun4_2      float64
amb4_2      float64
shar4_2     float64
attr2_2     float64
sinc2_2     float64
intel2_2    float64
fun2_2      float64
amb2_2      float64
shar2_2     float64
attr3_2     float64
sinc3_2     float64
intel3_2    float64
fun3_2      float64
amb3_2      float64
attr5_2     float64
sinc5_2     float64
intel5_2    float64
fun5_2      float64
amb5_2      float64
you_call    float64
them_cal    float64
date_3      float64
numdat_3    float64
num_in_3    float64
attr1_3     float64
sinc1_3     float64
intel1_3    float64
fun1_3      float64
amb1_3      float64
shar1_3     float64
attr7_3     float64
sinc7_3     float64
intel7_3    float64
fun7_3      float64
amb7_3      float64
shar7_3     float64
attr4_3     float64
sinc4_3     float64
intel4_3    float64
fun4_3      float64
amb4_3      float64
shar4_3     float64
attr2_3     float64
sinc2_3     float64
intel2_3    float64
fun2_3      float64
amb2_3      float64
shar2_3     float64
attr3_3     float64
sinc3_3     float64
intel3_3    float64
fun3_3      float64
amb3_3      float64
attr5_3     float64
sinc5_3     float64
intel5_3    float64
fun5_3      float64
amb5_3      float64
dtypes: float64(174), int64(13), object(8)
memory usage: 12.5+ MB